# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata_amps',
            name='batt_pow',
            field=models.FloatField(null=True),
        ),
    ]
