# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rawdata_amps_batt_pow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata_amps',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='date logged'),
        ),
        migrations.AlterField(
            model_name='rawdata_weather',
            name='winddir',
            field=models.IntegerField(null=True),
        ),
    ]
