# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20170402_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata_weather',
            name='humidity',
            field=models.FloatField(null=True),
        ),
    ]
