# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 04:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20170402_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata_weather',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='date logged'),
        ),
    ]
